FROM bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
# Python3 is needed to run the hadoop streaming job submission script
RUN apt-get update && apt-get install -y python3 && rm -rf /var/lib/apt/lists/*
